// src/components/CanvasControlFlow.tsx
import { lazy } from "react";
const Canvas = lazy(() => import("./Canvas"));
const OffscreenCanvas = lazy(() => import("./OffscreenCanvas"));

export function CanvasControlFlow() {
  return (
    <>
      {HTMLCanvasElement.prototype.transferControlToOffscreen ? (
        <OffscreenCanvas />
      ) : (
        <Canvas />
      )}
    </>
  );
}

// src/components/CanvasControlFlow.svelte
<script>
  import { onMount } from "svelte";

  let selectedCanvas;

  onMount(async () => {
    if (HTMLCanvasElement.prototype.transferControlToOffscreen) {
      selectedCanvas = (await import(`./OffscreenCanvas.svelte`)).default;
    } else {
      selectedCanvas = (await import(`./Canvas.svelte`)).default;
    }
  });
</script>

<svelte:component this={selectedCanvas} />
