// src/components/ClockWidget.svelte
<script lang="ts">
  import { onDestroy } from "svelte";
  import Text from "./Text.svelte";

  let time = new Date().toLocaleTimeString("en-US", {
    hour: "numeric",
    minute: "numeric",
    timeZone: "Asia/Singapore",
  });

  const timerId = setInterval(() => {
    time = new Date().toLocaleTimeString("en-US", {
      hour: "numeric",
      minute: "numeric",
      timeZone: "Asia/Singapore",
    });
  }, 15000);

  onDestroy(() => {
    clearInterval(timerId);
  });
</script>

<Text size="small" className="tabular-nums">
  {time} (GMT+8)
</Text>

// src/components/ClockWidget.tsx
import { useEffect } from "react";
import { useObservable } from "@legendapp/state/react";
import { Text } from "./Text";

export function ClockWidget() {
  const time = useObservable(
    new Date().toLocaleTimeString("en-US", {
      hour: "numeric",
      minute: "numeric",
      timeZone: "Asia/Singapore",
    })
  );

  useEffect(() => {
    const timerId = setInterval(() => {
      time.set(
        new Date().toLocaleTimeString("en-US", {
          hour: "numeric",
          minute: "numeric",
          timeZone: "Asia/Singapore",
        })
      );
    }, 15000);
    return () => {
      clearInterval(timerId);
    };
  }, []);

  return (
    <Text size="small" className="tabular-nums">
      {time} (GMT+8)
    </Text>
  );
}
